version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - cat ./daemon.yaml
      - aws cloudformation package --template-file ./daemon.yaml --s3-bucket "$PIPELINE_ARTIFACT_BUCKET" --s3-prefix cfn-packaged --output-template-file ./daemon.yaml.packaged
      - cat ./daemon.yaml.packaged
artifacts:
  type: zip
  files:
    - '**/*'
